# railway.toml

[build]
command = "composer install --no-dev --optimize-autoloader && php artisan config:cache"

[deploy]
postDeployCommand = "php artisan storage:link"

[start]
command = "php artisan serve --host=0.0.0.0 --port=8080"

[env]
APP_ENV = "production"
APP_URL = "https://laravue-api-production.up.railway.app"
FILESYSTEM_DISK = "public"
PORT = "8080"